steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-east1-docker.pkg.dev/${PROJECT_ID}/superbench/superbench', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'asia-east1-docker.pkg.dev/${PROJECT_ID}/superbench/superbench']